services:
  inner-x10Bot-redis:
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  inner-x10Bot-app:
    build: .
    image: x10-inner-bot-app
    working_dir: /usr/src/app
    environment:
      - REDIS_HOST=inner-x10Bot-redis
      - PGHOST=inner-x10Bot-postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
    depends_on:
      - inner-x10Bot-redis
      - inner-x10Bot-postgres
    ports:
      - "3001:3000"
    restart: always

  inner-x10Bot-postgres:
    image: postgres:15-alpine
    container_name: inner-x10Bot-postgres
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${PGNAME}
    ports:
      - "5432:5432"
    volumes:
      - x10-inner-bot_postgres_data:/var/lib/postgresql/data
    restart: always

  inner-x10Bot-report-service:
    build: .
    image: x10-inner-bot-report-service
    working_dir: /usr/src/app
    command: sh -c "node dist/src/services/reportService.js"
    environment:
      - PGHOST=inner-x10Bot-postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SERVICE_TYPE=report
    depends_on:
      - inner-x10Bot-postgres
    restart: always

volumes:
  x10-inner-bot_postgres_data: